<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
    <!-- Emotion Chart - Takes 2/3 of the grid -->
    <div class="col-span-1 md:col-span-1 lg:col-span-2 bg-white p-4 md:p-6 rounded-3xl shadow-sm">
        <div class="flex flex-col sm:flex-row sm:justify-between sm:items-center mb-4 gap-3 sm:gap-0">
            <div>
                <h3 class="text-lg font-semibold text-gray-800">Perjalanan Emosimu Sepanjang Minggu</h3>
                <p class="text-sm text-gray-600">Pantau fluktuasi emosi harian dan temukan pola yang bisa kamu sadari
                    lebih
                    awal.</p>
            </div>
            <select class="border border-gray-300 rounded-lg px-3 py-2 text-sm w-full sm:w-auto">
                <option>7 Hari terakhir</option>
            </select>
        </div>

        <!-- Chart -->
        <div class="flex items-end justify-between h-32 sm:h-40 md:h-48 mb-4" id="emotionChart">
            <!-- Chart bars will be generated by JavaScript -->
        </div>

        <!-- Legend -->
        <div class="grid grid-cols-2 sm:flex sm:flex-wrap gap-2 sm:gap-4 text-sm">
            <div class="flex items-center">
                <div class="w-3 h-3 bg-red-400 rounded-full mr-2"></div>
                <span class="text-gray-600">😊 Bahagia</span>
            </div>
            <div class="flex items-center">
                <div class="w-3 h-3 bg-gray-600 rounded-full mr-2"></div>
                <span class="text-gray-600">😐 Netral</span>
            </div>
            <div class="flex items-center">
                <div class="w-3 h-3 bg-red-500 rounded-full mr-2"></div>
                <span class="text-gray-600">😠 Marah</span>
            </div>
            <div class="flex items-center">
                <div class="w-3 h-3 bg-yellow-400 rounded-full mr-2"></div>
                <span class="text-gray-600">😰 Kecewa</span>
            </div>
            <div class="flex items-center">
                <div class="w-3 h-3 bg-red-600 rounded-full mr-2"></div>
                <span class="text-gray-600">😢 Sedih</span>
            </div>
            <div class="flex items-center">
                <div class="w-3 h-3 bg-gray-800 rounded-full mr-2"></div>
                <span class="text-gray-600">😴 Menangis</span>
            </div>
        </div>
    </div>

    {{-- Music --}}
    <div
        class="col-span-1 md:col-span-1 lg:col-span-1 gradient-red text-white pt-4 rounded-2xl relative overflow-hidden">

        {{-- gambar yang dimaksud --}}
        <img src="{{ asset('assets/member-dashboard/images/music-vector.png') }}"
            class="absolute top-5 -right-3 w-24 h-24 md:w-32 md:h-32 opacity-75 pointer-events-none" alt="Music Vector"
            style="mask-image: linear-gradient(to bottom, white 70%, transparent 100%); -webkit-mask-image: linear-gradient(to bottom, white 70%, transparent 100%);">

        <h3 class="font-semibold mb-2 text-lg md:text-xl text-center">
            Biarkan Musik Menenangkan Harimu
        </h3>
        <p class="text-base md:text-lg opacity-90 mb-4 text-center">
            Putar musik pilihan untuk bantu kamu melepas stres, mengatur napas, dan kembali fokus.
        </p>

        {{-- ini bagian container bawah --}}
        <div class="bg-white pb-6 pt-6 relative z-10">
            @include('member.pages.dashboard.components.music-item', [
                'image' => 'assets/member-dashboard/images/dummy-music-1.png',
                'title' => 'Fokus & Konsentrasi',
                'subtitle' => '2 Lagu',
                'link' => '#'
            ])
            @include('member.pages.dashboard.components.music-item', [
                'image' => 'assets/member-dashboard/images/dummy-music-2.png',
                'title' => 'Istirahat & Tidur',
                'subtitle' => '5 Lagu',
                'link' => '#'
            ])

            @include('member.pages.dashboard.components.music-item', [
                'image' => 'assets/member-dashboard/images/dummy-music-3.png',
                'title' => 'Suara Alam',
                'subtitle' => '8 Lagu',
                'link' => '#'
            ])
        </div>
        
    </div>
</div>